export const ActionTypes = {
  SAVE_NEW_BILL_REQUEST: 'SAVE_NEW_BILL_REQUEST',

  SET_INCREMENTAL_ID_REQUEST: 'SET_INCREMENTAL_ID_REQUEST',

  GET_ALL_BILL_REQUEST: 'GET_ALL_BILL_REQUEST',
  GET_ALL_BILL_SUCCESS: 'GET_ALL_BILL_SUCCESS',
  GET_ALL_BILL_ERROR: 'GET_ALL_BILL_ERROR',

  EDIT_EXISTING_BILL_REQUEST: 'EDIT_EXISTING_BILL_REQUEST',

  REMOVE_EXISTING_BILL_REQUEST: 'REMOVE_EXISTING_BILL_REQUEST',
};
